# Generated by Django 2.1.5 on 2019-02-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
